### PR TITLE
Check for null trkseg when parsing GPX. Fixes #50

### LINKED ISSUE #50: ArgumentNullException parsing valid GPX track
As per the spec, a `<trk>` element may contain zero or more `<trkseg>` elements. However, this library will throw an exception parsing them.

cf https://www.topografix.com/GPX/1/1/gpx.xsd

### PR DESCRIPTION
**Pull request by mfeingol**
Hi, @sibartlett. Hopefully this is simple enough.

### CODE REVIEW

**Comment by mfeingol** [comment]
@sibartlett: another gentle ping on this. Thanks.

**Comment by mfeingol** [comment]
@sibartlett: another ping. Thanks.

**Comment by mfeingol** [comment]
@sibartlett: still hitting this in the wild. Any chance you could push the PR through?

Thanks!

**Comment by sibartlett** [comment]
Hi Max,
Sorry for taking almost two years to merge and publish this PR, please forgive me.

**Comment by mfeingol** [comment]
@sibartlett: no worries. Thanks for the merge!

**Comment by sibartlett** [comment]
I will try and keep on top of things a bit more moving forward. I've started a new job, and am getting back into .NET development after an almost ten year hiatus.

**Comment by mfeingol** [comment]
Congratulations, and welcome back to the light side!

**Pull request merged**
