### PR TITLE
Improve GPX compatibility

### PR DESCRIPTION
**Pull request by sibartlett**
* Use `Waypoint` for all GPS data
* Removed `Fix`

### CODE REVIEW

**Comment by sibartlett** [comment]
@mfeingol please take a look :)

**Comment by mfeingol** [comment]
Thanks, @sibartlett, these changes look great!

The commit is very similar to a commit I started but stashed away, because they seemed too extensive to justify from my particular need. But I think ultimately this is the right thing to do, and it makes sense to make all breaking changes in a single version increment.

Thanks again.

**Comment by sibartlett** [comment]
What .NET version are you using @mfeingol ?

Wondering if it's worth migrating the library to nullable reference types, seeing that this will be a whole new version?

**Comment by mfeingol** [comment]
Personally I'm using Geo with UWP (.NET Core 2.2) And Xamarin Forms for Android (Mono).

That said, I don't think it matters. My understanding is that you can enable this feature for a library and continue to emit assemblies for versions older than .NET Standard 2.1, simply by using C# 8.0 in your project and continuing to multi-target.

I have yet to start using nullable reference types in a large project, but it seems like a really good idea.

https://devblogs.microsoft.com/dotnet/embracing-nullable-reference-types/
https://stackoverflow.com/questions/56651472/does-c-sharp-8-support-the-net-framework

**Pull request merged**
