### PR TITLE
Update Geo library

### PR DESCRIPTION
**Pull request by mfeingol**
Commits largely speak for themselves. The gist is:

- Update to .NET Standard 1.4
- Address several GPX serialization bugs
- Improve the tests for GPX serialization to catch those and similar issues
- Update to latest NUnit.
- Address several miscellaneous other bugs, some found by others in the sibartlett/Geo repo

### CODE REVIEW

**Comment by sibartlett** [comment]
Thanks for the pull request!

Would you be interested in being added to the project as a maintainer?

**Comment by mfeingol** [comment]
Hi, Simon. Thanks for the offer, and sure, that would be great. If there's an occasional PR for the project, I wouldn't mind taking a look.

My interest in Geo is mainly as a user. I have a travel planning app that uses it quite a bit for GPX reading/writing, so that's where my main interest lies.

What would it take to get a fresh NuGet package released through your official channel?

**Comment by mfeingol** [comment]
I've updated this PR to include one additional fix in `fd8f01f`.

@sibartlett: let me know what you'd like to do with this PR.

**Comment by andrewlock** [comment]
Any chance that this will be merged soon? 🙂

Also, can I make a suggestion/request? Guidance is to not target only .NET Standard 1.x only, as it results in very large dependency graphs for frameworks that support .NET Standard 2.0. You can [see the full guidance here](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting), but to save you some reading, I suggest changing this line:

```xml
<TargetFramework>netstandard1.4</TargetFramework>
```

with this (note the `s` on `TargetFrameworks`):

```xml
<TargetFrameworks>netstandard1.4;netstandard2.0;net461;net472</TargetFrameworks>
```

This gives you the best of all worlds - wide compatibility thanks to .NET Standard 1.x, a good experience for .NET Core apps, and avoids library issues caused by the .NET Framework 4.6.1 compatibility shim!

**Comment by mfeingol** [comment]
@andrewlock: thanks for the note. I updated the target frameworks and bumped the version.

As for when this will be merged... that's a question for @sibartlett. :-)

**Comment by jcvandan** [comment]
I would also be interested in whether this will be released - I was just about to have a crack at it myself. I can reference the package from a .NET Core 2.2 project but get a shed load of compiler warnings (even though it works!).

**Comment by sibartlett** [comment]
Sorry everyone for my lack of activity here. I do want to get this merged, I haven’t had all that much free time.

This isn’t a quick thing for me to do, I haven’t done much .NET in the past 5 years, so will need to get reacquainted with things.

I did mention adding other maintainers would help, but I still need to connect my NuGet account to a Microsoft account. I will try and do that this week, then maybe I can add some people to the project.

**Comment by mfeingol** [comment]
@sibartlett: glad to hear, thanks. Let me know if you have any questions about anything.

**Comment by sibartlett** [comment]
Merged in: 8d04f7db5078a95fdf0e118fea18b0f4881ab836

**Comment by sibartlett** [comment]
All the pull requests have been merged.

I wil try and figure out the NuGet situation within the next week.

**Comment by sibartlett** [comment]
Sorry, that’s it’s been taking me a while to get around to doing this. I’m now actively working to get the Nuget package republished.

I’ve been trying to understand changes around build targets and NuGet since I last used .NET several years ago.

I’m trying to clean the project files up, to better understand things.

Would it be problematic if I only publish a .NET standard 2.0 version?

I understand that this PR updated the project to 1.4, but i don’t understand how the XML stuff was working? Doesn’t seem the XML classes we are using, are available in .NET standard 1.4?

**Comment by jcvandan** [comment]
@sibartlett .NET Standard 2.0 won't be an issue, it's compatible with .NET Core 2 and up.

**Comment by mfeingol** [comment]
@sibartlett: for what it's worth, I'm able to build multitargeted Geo for 1.4 and 2.0 without any build problems here.

**Comment by sibartlett** [comment]
Thanks for the reply @mfeingol 

How do you get `System.Xml.Serialization` namespace to compile in .NET Standard 1.4?

For instance, the official documentation states that [`XmlElementAttribute`](https://docs.microsoft.com/en-us/dotnet/api/system.xml.serialization.xmlelementattribute?view=netstandard-2.0&viewFallbackFrom=netstandard-1.4) is not available in 1.4

**Comment by mfeingol** [comment]
>How do you get System.Xml.Serialization namespace to compile in .NET Standard 1.4?

System.Xml.XmlSerializer NuGet package.

**Comment by sibartlett** [comment]
Ahhh... sorry, me being dumb 😄 

I'm just trying things with a brand new .csproj - and I missed that part.

**Comment by sibartlett** [comment]
I spent a few hours figuring things out. I cleaned up the solution a bit too; updated the .csproj files, removed the .nuspec files, etc.

The NuGet package is finally updated, published as version [0.20.0](https://www.nuget.org/packages/Geo/).

**Comment by mfeingol** [comment]
Thanks, a lot, @sibartlett!

**Comment by jcvandan** [comment]
Thanks from NW UK as well @sibartlett, much appreciated! I'll do what I can to help contirb in the future.

**Pull request closed without merging**
